[build]
command = "rm -rf __obsidian __site && mkdir __obsidian && mv * __obsidian || true && git clone -b dev https://github.com/ppeetteerrs/obsidian-zola.git __site && __site/run.sh"
publish = "public"

[build.environment]
GANALYTICS = "G-GXRDN10PHJ"
HOME_GRAPH = ""
LANDING_BUTTON = "<span class='shake-rotate shake-freeze'>Click to steal some👆</span>"
LANDING_DESCRIPTION = "My physical brain is <span class='shake-rotate shake-freeze' style='font-size: 2rem'> 💤 </span> but my digital brain is available."
LANDING_PAGE = "home"
LANDING_TITLE = "Welcome!"
PAGE_GRAPH = ""
PYTHON_VERSION = "3.8"
REPO_URL = "https://github.com/ppeetteerrs/obsidian-pkm"
SITE_TITLE = "Peter's 2<sup>nd</sup> <span class='hvr-pulse'>🧠</span>"
SITE_TITLE_TAB = "Peter's Second 🧠"
SITE_URL = "https://peteryuen.netlify.app/"
SLUGIFY = ""
TIMEZONE = "Asia/Hong_Kong"
ZOLA_VERSION = "0.15.2"
